[2025-10-17T09:09:00.160+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.get_data scheduled__2025-10-16T20:00:00+00:00 [queued]>
[2025-10-17T09:09:00.167+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.get_data scheduled__2025-10-16T20:00:00+00:00 [queued]>
[2025-10-17T09:09:00.167+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-17T09:09:00.178+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_data> on 2025-10-16 20:00:00+00:00
[2025-10-17T09:09:00.183+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2025-10-17T09:09:00.188+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'get_data', 'scheduled__2025-10-16T20:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpxqud9a8k']
[2025-10-17T09:09:00.191+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask get_data
[2025-10-17T09:09:00.244+0000] {task_command.py:416} INFO - Running <TaskInstance: csv_etl_pipeline.get_data scheduled__2025-10-16T20:00:00+00:00 [running]> on host 0c9ee2dc6164
[2025-10-17T09:09:00.312+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T20:00:00+00:00'
[2025-10-17T09:09:00.314+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-17T09:09:00.314+0000] {base.py:73} INFO - Using connection ID 'postgres_pg' for task execution.
[2025-10-17T09:09:00.325+0000] {warnings.py:109} WARNING - /opt/***/dags/etl.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM games", conn)

[2025-10-17T09:09:00.333+0000] {logging_mixin.py:154} INFO - Nombre de jeux : 3
[2025-10-17T09:09:00.334+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-10-17T09:09:00.343+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=csv_etl_pipeline, task_id=get_data, execution_date=20251016T200000, start_date=20251017T090900, end_date=20251017T090900
[2025-10-17T09:09:00.399+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T09:09:00.425+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
