[2025-10-17T09:10:16.835+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_etl_pipeline.get_data manual__2025-10-17T09:10:15.608680+00:00 [queued]>
[2025-10-17T09:10:16.844+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_etl_pipeline.get_data manual__2025-10-17T09:10:15.608680+00:00 [queued]>
[2025-10-17T09:10:16.844+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-10-17T09:10:16.857+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_data> on 2025-10-17 09:10:15.608680+00:00
[2025-10-17T09:10:16.862+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2025-10-17T09:10:16.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'csv_etl_pipeline', 'get_data', 'manual__2025-10-17T09:10:15.608680+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpnnzf9mdu']
[2025-10-17T09:10:16.872+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask get_data
[2025-10-17T09:10:16.925+0000] {task_command.py:416} INFO - Running <TaskInstance: csv_etl_pipeline.get_data manual__2025-10-17T09:10:15.608680+00:00 [running]> on host 0c9ee2dc6164
[2025-10-17T09:10:17.011+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_etl_pipeline' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T09:10:15.608680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T09:10:15.608680+00:00'
[2025-10-17T09:10:17.013+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-17T09:10:17.013+0000] {base.py:73} INFO - Using connection ID 'postgres_pg' for task execution.
[2025-10-17T09:10:17.022+0000] {warnings.py:109} WARNING - /opt/***/dags/etl.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM games", conn)

[2025-10-17T09:10:17.028+0000] {logging_mixin.py:154} INFO - Nombre de jeux : 3
[2025-10-17T09:10:17.028+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-10-17T09:10:17.037+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=csv_etl_pipeline, task_id=get_data, execution_date=20251017T091015, start_date=20251017T091016, end_date=20251017T091017
[2025-10-17T09:10:17.079+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T09:10:17.102+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
